name: scheduler

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
      - run: pnpm sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: brc-dd
          SPONSORKIT_OPENCOLLECTIVE_KEY: ${{ secrets.SPONSORKIT_OPENCOLLECTIVE_KEY }}
          SPONSORKIT_OPENCOLLECTIVE_SLUG: brc-dd
          SPONSORKIT_OPENCOLLECTIVE_TYPE: person
      - run: |
          git config --global user.name "Divyansh Singh"
          git config --global user.email "40380293+brc-dd@users.noreply.github.com"
          git add .
          git commit -m "chore: update sponsors" || :
          git push
